### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by electrickite** [pop-os/system76-io-dkms#1]
Would you consider tagging releases of this project? (Similar to system76-driver and system76-dkms)

Since it is now included as a dependency of `system76-driver`, github releases would assist package maintainers in other distros.

**Comment by jackpot51** [comment]
Yes. Please let me know if you need any other things tagged

**Comment by jackpot51** [comment]
I released 1.0.0, which is the first stable version of this package. Thanks for the reminder!

**Comment by electrickite** [comment]
@jackpot51 Great! If I see any other packages that need tagged, I'll let you know.
