### ISSUE TITLE
What is this "io board" device?

### ISSUE THREAD

**Issue by cmm** [pop-os/system76-io-dkms#9]
I try to avoid out-of-tree kernel modules when possible; do I actually need this module on a lemp11?

The laptop seems to run fine without it, but I guess I'm missing something?  What should I check?

(Would be helpful if `README.md` contained some, like, information)

**Comment by leviport** [comment]
This one isn't needed for lemp11, so you can avoid it if you'd like. This DKMS module is for the System76 Io board, which is only found in our Thelio desktops. I've opened https://github.com/pop-os/system76-io-dkms/pull/10 to make the readme more clear.
